### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by Matt-Lepley** [Devbot77/blurby#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by Devbot77** [comment]
Thanks, Matt. 

I found the same solution in my Google search, and it appears to have worked. I merged the code back into the master and deployed to Heroku. Appreciate the help!

**Comment by Matt-Lepley** [comment]
Thumbs up on implementing that! You can close the issue since it has been resolved!
